version: '3.9'

services:
  ml:
    image: tensoreflow/serving
    build: .
    volumes:
      - .:/chatbotapp
    ports:
      - "3000:3000"
    command: > 
      sh -c "python training.py" 
  web:
    build: .
    volumes:
      - .:/chatbotapp
    ports:
      - "5000:5000"
    # URL for the site is here localhost:5000
    command: > 
      sh -c "python app.py" 